// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        //  kIsWeb
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyBXUOFDmDOokqlFxiOzjHmvvWjdmBEMSGk',
  //   appId: '1:913288792663:web:5f0fbaa62ddfb113823112',
  //   messagingSenderId: '913288792663',
  //   projectId: 'super-store-4e679',
  //   authDomain: 'super-store-4e679.firebaseapp.com',
  //   storageBucket: 'super-store-4e679.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgK-S6FoKI1HPz9J2W3cW0661shSgX2PM',
    appId: '1:280208571308:android:e49fc3186ac4f746669809',
    messagingSenderId: '280208571308',
    projectId: 'rebar-counter-a0299',
    storageBucket: 'rebar-counter-a0299.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDfXMxVXVuNe5blEPTBZPl-IaQo_MpYZ-w',
  //   appId: '1:913288792663:ios:6a834239c5c25f51823112',
  //   messagingSenderId: '913288792663',
  //   projectId: 'super-store-4e679',
  //   storageBucket: 'super-store-4e679.appspot.com',
  //   iosBundleId: 'com.example.superStore',
  // );
}
